// <auto-generated />
using System;
using EstoqueService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstoqueService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110193728_AddPedidoAndProdutoPrecision")]
    partial class AddPedidoAndProdutoPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstoqueService.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PEDIDO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DSC_Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DSC_CLIENTE");

                    b.Property<DateTime>("DT_Pedido")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_PEDIDO");

                    b.Property<decimal>("NUM_ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NUM_VALOR_TOTAL");

                    b.HasKey("Id");

                    b.ToTable("TB_PEDIDO");
                });

            modelBuilder.Entity("EstoqueService.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUTO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DSC_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DSC_NAME");

                    b.Property<decimal>("NUM_UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NUM_UNIT_PRICE");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("QTD_STOCK")
                        .HasColumnType("int")
                        .HasColumnName("QTD_STOCK");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("TB_PRODUTO");
                });

            modelBuilder.Entity("EstoqueService.Models.Produto", b =>
                {
                    b.HasOne("EstoqueService.Models.Pedido", "Pedido")
                        .WithMany("Produtos")
                        .HasForeignKey("PedidoId");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("EstoqueService.Models.Pedido", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
